### ISSUE TITLE
Create a basic Host implementation

### ISSUE THREAD

**Issue by atoulme** [whiteblock/gossipsub-testing#1]
Create a basic Host implementation with go-libp2p. The program should start and expose a predetermined port (9000?).

**Comment by adam-hanna** [comment]
Under active development and will need a review from PL:

https://github.com/agencyenterprise/gossip-host

**Comment by adam-hanna** [comment]
@araskachoi can this be closed?

**Comment by araskachoi** [comment]
yesssir!
